### ISSUE TITLE
[Question]Can slam_toolbox deal with scans when the robot not on a flat surface?

### ISSUE THREAD

**Issue by joekeo** [SteveMacenski/slam_toolbox#107]
My question is if there is a way to filter out the scans when the robot is tilted in roll or pitch, or if this is a filter that we need to do ourselves to the /scan data that goes into the package?

**Comment by SteveMacenski** [comment]
No, this is purely 2D lidar SLAM

**Comment by SteveMacenski** [comment]
But lets say the robot is tilted "a little bit", you should still be able to map without much of a concern. I've done some tests of this on the sidewalk (cracks, going over lumps, driveways, etc) in a major US city and showed it worked OK.

If you're asking "will this work on a drone" my answer will be no better or worse than gmapping / karto since they both make the same assumption and handle it the same way I do.
