### ISSUE TITLE
[ROS2][BUG] Parameters already declared

### ISSUE THREAD

**Issue by maxlein** [SteveMacenski/slam_toolbox#135]
Another little bug here :)  

`smapper_->configure(shared_from_this());` gets called twice in `dashing-devel` and this leads to an ***parameter already declared*** exception.  

In my ingenuous world I just commented the line in `loadSerializedPoseGraph()` and it runs for the moment.

**Comment by SteveMacenski** [comment]
This is true, my bad. I need to slow down on the ROS1 patches -> ROS2. Apologies. 

This was added because I found that the serialized form of the params were being used in relocalization/continue mapping modes, not the new versions. 

Fix here is to have them declare parameters if not already declared or keep a bool for if configure has been called and then rather than declare it gets param. 

PRs welcome ;-)
