### ISSUE TITLE
libceres-dev ubuntu 20.04 not released yet - rosdep fails to install dependencies 

### ISSUE THREAD

**Issue by bgilreath** [SteveMacenski/slam_toolbox#208]
**Required Info:**

- Operating System: Ubuntu 20.04
  - 
- Installation type: from source
  - 
- ROS Version ROS1 Noetic
  - 
- Version or commit hash: noetic-devel 
  - 

#### Steps to reproduce issue

1. cd catkin_ws
2. rosdep install --from-paths src --ignore-src -r -y
3. catkin_make

#### Expected behavior
Expected to compile

#### Actual behavior
rosdep:
E: Package 'libceres-dev' has no installation candidate
ERROR: the following rosdeps failed to install
  apt: command [sudo -H apt-get install -y libceres-dev] failed
  apt: Failed to detect successful installation of [libceres-dev]

catkin_make:
CMake Error at slam_toolbox/slam_toolbox/CMakeLists.txt:39 (find_package):
  By not providing "FindCeres.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Ceres", but
  CMake did not find one.

  Could not find a package configuration file provided by "Ceres" with any of
  the following names:

    CeresConfig.cmake
    ceres-config.cmake

  Add the installation prefix of "Ceres" to CMAKE_PREFIX_PATH or set
  "Ceres_DIR" to a directory containing one of the above files.  If "Ceres"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/ubuntu/catkin_ws/build/CMakeFiles/CMakeError.log".
make: *** [Makefile:1552: cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed

#### Additional information
Just pointing out this issue.

**Comment by SteveMacenski** [comment]
>  E: Package 'libceres-dev' has no installation candidate

Your issue is that ceres hasn't been successfully released in 20.04 yet on ARM64 (and I suppose rosdep). This is actually a noted issue https://github.com/ceres-solver/ceres-solver/issues/599 https://bugs.launchpad.net/ubuntu/+source/ceres-solver/+bug/1882626 to me recently and its being slowly dealt with.

Since this isn't actually an issue with slam toolbox, but rather an unreleased dependency (also why you dont see a Noetic or Foxy release for this yet), I'm going to close this ticket. But I do really appreciate you bringing this to my attention, but for the moment, there's nothing I can do about it. We're both in a waiting pattern for Ceres support for 20.04, after which I will test and release slam toolbox as well. For now, I recommend reverting to Melodic. There's a number of other packages not available in Noetic yet that I think you should revert if this blocks you (because other things will certainly block you too).

**Comment by SteveMacenski** [comment]
You know what, I lied, I'm going to keep this open so I have a note about this to remind me to deal with this once its been released.
