### ISSUE TITLE
Covariance matrix of the robot pose on localization mode

### ISSUE THREAD

**Issue by vsamy** [SteveMacenski/slam_toolbox#427]
#### Feature description

On localization mode, it would be nice to have the covariance matrix of the robot pose.
It is a good indicator to know whether the robot is lost or not.

#### Implementation considerations

The covariance matrix seems to already be implemented in the function `process` of `Mapper.cpp` so it could be exposed along the computation of the bestPose

**Comment by adamkrawczyk** [comment]
It would be helpful to me too, so I will implement that and do a PR.

**Comment by adamkrawczyk** [comment]
@SteveMacenski What would be a nice way to expose this data?

**Comment by mattberkem** [comment]
I was also looking for something like this. The covariance is one possibility. I don't know how it is calculated for SLAM Toolbox and whether it will meaningfully indicate convergence. So what about instead of, or in addition to, the quantity that is being optimized by the solver? Maybe this also needs to be normalized and/or scaled, I don't know. Since a nonlinear optimization is being performed, I would guess there is some quantity that would initially be large, when the solution was poor, which would then decrease as the fit (laser scans on top of map features) became better. I would be interested in exploring whether this quantity could also be exposed.
But then I realize this could be hard since it seems that SLAM Toolbox adds to the map in localization mode when the scans don't fit the starting map, but maybe there is a quantity that gives the error with respect to the "established" map, if that makes any sense.

**Comment by SteveMacenski** [comment]
#508 implements
