### ISSUE TITLE
Possible to do re-localization in the life-long-slam mode?

### ISSUE THREAD

**Issue by xingjl6280** [SteveMacenski/slam_toolbox#522]
#### Feature description
I want to try the life-long slam mode in the real world. 
The problem is the robot might be turned on anywhere, therefore need to manually re-localization. 
Is that possible to let the life-long node subscribe and process initialpose just like the pure localization node?

**Comment by SteveMacenski** [comment]
Lifelong SLAM mode is a not super functional prototype under `experimental`, so in all honesty this is kind of a moot question because that mode is not really ready for prime-time use (hence why its in `experimental`). 

But conceptually, you can set the initial pose when you deserialize your slam graph to provide it with the initial location, but you cannot manually re-localize after that point (nor could you with any other slam mode).
