### ISSUE TITLE
Slam_toolbox build fails inside the docker 

### ISSUE THREAD

**Issue by TahaChouik** [SteveMacenski/slam_toolbox#600]
**Required Info:**

- Operating System:
  - OS and version (Ubuntu 20.04)
- Installation type:
  - from source: branch ros2 foxy-devel 
- ROS Version
  - ROS2 foxy
- Version or commit hash:
  - 4786e90
  
#### Steps to reproduce issue
I encountered an issue while building slam_toolbox inside a a docker.  
I started by creating a Docker image based on the "dustynv/ros:foxy-ros-base-l4t-r35.2.1" base image. In the Dockerfile i followed these instructions to install eigen3 :

```
WORKDIR /home/
RUN git clone https://gitlab.com/libeigen/eigen.git --recursive
WORKDIR /home/eigen
RUN mkdir -p build
WORKDIR /home/eigen/build
RUN cmake ..
RUN make install
```
Additionally, I installed all the dependencies via rosdep. However, the build process for slam_toolbox fails.

 

#### Expected behavior
All packages build successfully

#### Actual behavior
I receive the following stderr message when i tried to do colcon build inside the docker : [stdout_stderr.log](https://github.com/SteveMacenski/slam_toolbox/files/11576837/stdout_stderr.log)

#### Additional information
I think eigen3 is causing the problem.

**Comment by SteveMacenski** [comment]
Foxy is EOL an will receive no further support but...

You're bringing up the use of Nvidia's docker base images which might not match versions important for ROS packages to operate per REP 2000's versioning expectations. Further, you're manually building Eigen instead of using the binaries that are expected. The errors you bring up are clearly related to serializing Eigen so I'm guessing its specifically because you're not using the packaged version of Eigen.  There are version of eigen that ship with a distribution / linux OS for exactly this kind of compatiability problem resolution that should be relied upon, not just installing bleeding-edge the way that you are by cloning its default branch. 

I make no statement about compilation if you go off the beaten path of versioning that the distribution and OS expect for super core libraries.
