### ISSUE TITLE
Determination for known regions

### ISSUE THREAD

**Issue by Hao-Li-Bachelorarbeit** [SteveMacenski/slam_toolbox#653]
**Required Info:**

- Operating System:
  - Ubuntu 22.04
- Installation type:
  - binaries
- ROS Version
  - ROS2 HUMBLE
- Version or commit hash:
  - 
- Laser unit:
  - 
  
#### Steps to reproduce issue
Hi, I've noticed that the map building area of the slam_toolbox is always too small when the robot newly arrives at a pose, whereas, for example, it is only after a rotation that a more reasonable map is obtained, as shown in the picture:
before spin:
![before spin](https://github.com/SteveMacenski/slam_toolbox/assets/141755843/ff01fafb-a7e1-4b80-a90c-1df37eb5f5b6)
after spin:
![after spin](https://github.com/SteveMacenski/slam_toolbox/assets/141755843/9f8c4d56-59d8-4ba9-b404-c776c0a235e3)
I'm not sure if this is a bug or a feature, and if it is a feature, is it a resolution issue with the laser scan? But as you can see in the picture, the laser dots on the obstacle are still very dense, and in the area close to the obstacle, it should also be open space at the beginning.

**Comment by SteveMacenski** [comment]
It is definitely related to your sensor's resolution. You need enough unique sensor readings of "this is free space" for each cell to count it. That's why near the robot you get some map showing up because enough individual rays overlap enough of the cells to make them count. When you rotate, you trigger another update (or multiple) whos data then also shows from another viewpoint that its clear so then more of the space appears

**Comment by Hao-Li-Bachelorarbeit** [comment]
ok, thank you!
