### ISSUE TITLE
Asymmetric laser scan angle limits cause misalignment between scans and map grid cells during mapping

### ISSUE THREAD

**Issue by KishanSawant** [SteveMacenski/slam_toolbox#734]
**Required Info:**

- Operating System:
  - Ubuntu 24.04
- Installation type:
  - binaries
- ROS Version
  - ROS2 Jazzy
- Gazebo version
  -  Gazebo Harmonic
- Version or commit hash:
  - feature/nav2
- Laser unit:
  - gpu_lidar (in Gazebo)
  
#### Steps to reproduce the issue

Update the laser angle limits in the urdf file:

**test1:** symmetric limits
            max_angle="1.7"
            min_angle="-1.7"

**test2:** asymmetric limits
            max_angle="2.1"
            min_angle="-1.7"

Run the mapping launch file:
`ros2 launch slam_toolbox online_sync_launch.py`

**Config file:** mapper_params_online_async.yaml
[mapper_params_online_async.md](https://github.com/user-attachments/files/17961448/mapper_params_online_async.md)

#### Expected behavior
For test1:
![symmetric](https://github.com/user-attachments/assets/70d91056-fbab-4cad-96e0-b863691c0219)

#### Actual behavior
For test2:
![asymmetric](https://github.com/user-attachments/assets/e53d5867-f68b-4298-b571-d1ba5b97c5ba)

#### Additional information
For test2, the issue persists even after completely mapping the environment

**Comment by SteveMacenski** [comment]
That is not surprising to me - it is a non-feature that the FOVs of lidars are non-symmetric. You can make this virtually symmetric by using a Laser Filter to set the values of the filtered angles to `0.0`, or `INF` so that they are not considered. That would create a data structure for the internal SLAM that is symmetric, whereas the ~`0.4` missing would be replaced by non-values
