### ISSUE TITLE
Disappearing map?

### ISSUE THREAD

**Issue by msadowski** [SteveMacenski/slam_toolbox#91]
Hi Steve!

Thanks for the great package! I'm currently running some tests and it's the first SLAM package I used that works very well out of the box.

It's very well possible that I've missed some parameter or something else in the docs but is the disappearing map the valid behaviour of slam_toolbox?

Here is how it looks like for me in the simulation (I believe I've seen it happened on real robot too):

![slam_toolbox_map_erase](https://user-images.githubusercontent.com/6543766/64613074-91419580-d3d5-11e9-9188-cbf7c011394b.gif)

The map shown in the window above is the one appearing on map topic.

Any feedback you might have would be highly appreciated!

**Comment by SteveMacenski** [comment]
In localization mode, yes that’s valid behavior. What’s your launch file/config?

The method I implement for localization keeps a rolling window of scans to process and localize against so that you’re localized against both the map itself as well as the local set of features of the real environment rather than throwing out the current state as “junk” to be removed from processing the core map. This rolling window will expire and then the scans and their constraints/nodes will depreciate and disappear from the map. 

So if you input no base map, there’s a “pure” sliding window localization on based on the current state of the world. If you input the map before localization you’ll see the map refine itself in the local time horizon but then revert back to the original map when leaving a region. 

But this is unique of localization mode. Slam modes should not remove elements from the graph. 

And thanks! I’ve worked very hard to make that happen :-)

Edit: its much more satisfying maintaining a SLAM package... people post gifs that make it _way_ easier

**Comment by msadowski** [comment]
Thanks a lot for a quick answer and an explanation! When I wrote the issue I was indeed running the `localization.launch` file. Switching to online_async.launch file the mapping is working well!

I'll be working with slam_toolbox for the next couple of days. If you need any help with then let me know, I'm happy to help! 

I found the gifs to be really good in sharing results (especially in RVIZ). I found peek to be very useful tool for that: https://github.com/phw/peek

Closing this. Once again thanks for help!

**Comment by SteveMacenski** [comment]
@msadowski side note: if you make a nice gif of you mapping a space, I'd love to include it in the readme with a shoutout. I'm always looking for good demonstrations of my work in use.

**Comment by msadowski** [comment]
@SteveMacenski It's quite likely that I'll write a blog post about slam_toolbox together with [Robosynthesis](https://www.robosynthesis.com//) in the near future. When I do I'll make sure to make some nice gifs/videos that you could also use.

**Comment by SteveMacenski** [comment]
Awesome! I'm also starting my deck for my talk at [ROSCon](https://roscon.ros.org/2019/), and I love visuals over words 6 days out of the week.

**Comment by msadowski** [comment]
@SteveMacenski I put together a small article on our first trials with the package! You can find it here: https://www.robosynthesis.com/post/hands-on-with-slam_toolbox . If you find any of the images or gifs usable for you then feel free to use them!
